import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useDispatch } from 'react-redux';
import {
  Box,
  Typography,
  Paper,
  TextField,
  Button,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  Alert,
  Grid,
  Divider,
} from '@mui/material';
import { Save as SaveIcon, Cancel as CancelIcon } from '@mui/icons-material';
import { createDnaProfile } from '../../store/dnaSlice';
import type { AppDispatch } from '../../store/store';

export default function DnaCreatePage() {
  const navigate = useNavigate();
  const dispatch = useDispatch<AppDispatch>();

  const [formData, setFormData] = useState({
    projectName: '',
    testing: 'standard',
    risk: 'medium',
    autonomy: 'high',
    customTools: '',
    constraints: '',
  });

  const [error, setError] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);

  const handleChange = (field: string, value: string) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
    setError(null);
  };

  const handleSubmit = async () => {
    // Validation
    if (!formData.projectName.trim()) {
      setError('Project name is required');
      return;
    }

    setSubmitting(true);
    setError(null);

    try {
      const result = await dispatch(createDnaProfile({
        dnaCode: '', // Will be generated by backend
        projectName: formData.projectName,
        testing: formData.testing,
        risk: formData.risk,
        autonomy: formData.autonomy,
        customTools: formData.customTools || undefined,
        constraints: formData.constraints || undefined,
      })).unwrap();

      // Navigate to the created profile
      navigate(`/dna-profiles/${result.dnaCode || result.profile?.dnaCode}`);
    } catch (err: any) {
      setError(err.message || 'Failed to create DNA profile');
      setSubmitting(false);
    }
  };

  const handleCancel = () => {
    navigate('/dna-profiles');
  };

  return (
    <Box>
      <Typography variant="h4" gutterBottom>
        Create DNA Profile
      </Typography>
      <Typography variant="body2" color="text.secondary" paragraph>
        Configure project-level preferences that will apply to all SPECs under this DNA profile.
      </Typography>

      <Paper sx={{ p: 3, mt: 3 }}>
        {error && (
          <Alert severity="error" sx={{ mb: 3 }}>
            {error}
          </Alert>
        )}

        <Grid container spacing={3}>
          {/* Project Name */}
          <Grid item xs={12}>
            <TextField
              fullWidth
              label="Project Name"
              required
              value={formData.projectName}
              onChange={(e) => handleChange('projectName', e.target.value)}
              placeholder="e.g., My SPEC Engine Project"
              helperText="A descriptive name for your project"
            />
          </Grid>

          <Grid item xs={12}>
            <Divider>
              <Typography variant="body2" color="text.secondary">
                Preferences
              </Typography>
            </Divider>
          </Grid>

          {/* Testing Approach */}
          <Grid item xs={12} md={4}>
            <FormControl fullWidth>
              <InputLabel>Testing Approach</InputLabel>
              <Select
                value={formData.testing}
                label="Testing Approach"
                onChange={(e) => handleChange('testing', e.target.value)}
              >
                <MenuItem value="basic">Basic - Essential tests only</MenuItem>
                <MenuItem value="standard">Standard - Balanced testing</MenuItem>
                <MenuItem value="comprehensive">Comprehensive - Extensive testing</MenuItem>
              </Select>
            </FormControl>
          </Grid>

          {/* Risk Tolerance */}
          <Grid item xs={12} md={4}>
            <FormControl fullWidth>
              <InputLabel>Risk Tolerance</InputLabel>
              <Select
                value={formData.risk}
                label="Risk Tolerance"
                onChange={(e) => handleChange('risk', e.target.value)}
              >
                <MenuItem value="low">Low - Cautious approach</MenuItem>
                <MenuItem value="medium">Medium - Balanced risk</MenuItem>
                <MenuItem value="high">High - Aggressive approach</MenuItem>
              </Select>
            </FormControl>
          </Grid>

          {/* Autonomy Level */}
          <Grid item xs={12} md={4}>
            <FormControl fullWidth>
              <InputLabel>Autonomy Level</InputLabel>
              <Select
                value={formData.autonomy}
                label="Autonomy Level"
                onChange={(e) => handleChange('autonomy', e.target.value)}
              >
                <MenuItem value="low">Low - Frequent human input</MenuItem>
                <MenuItem value="medium">Medium - Balanced autonomy</MenuItem>
                <MenuItem value="high">High - Minimal intervention</MenuItem>
              </Select>
            </FormControl>
          </Grid>

          {/* Custom Tools (Optional) */}
          <Grid item xs={12}>
            <TextField
              fullWidth
              label="Custom Tools (Optional)"
              multiline
              rows={2}
              value={formData.customTools}
              onChange={(e) => handleChange('customTools', e.target.value)}
              placeholder="e.g., specific libraries, frameworks, or tools to use"
              helperText="Comma-separated list of tools or frameworks preferred for this project"
            />
          </Grid>

          {/* Constraints (Optional) */}
          <Grid item xs={12}>
            <TextField
              fullWidth
              label="Constraints (Optional)"
              multiline
              rows={3}
              value={formData.constraints}
              onChange={(e) => handleChange('constraints', e.target.value)}
              placeholder="e.g., must support offline mode, performance requirements, security constraints"
              helperText="Any specific constraints or requirements for SPECs in this project"
            />
          </Grid>
        </Grid>

        <Box mt={4} display="flex" gap={2} justifyContent="flex-end">
          <Button
            variant="outlined"
            startIcon={<CancelIcon />}
            onClick={handleCancel}
            disabled={submitting}
          >
            Cancel
          </Button>
          <Button
            variant="contained"
            startIcon={<SaveIcon />}
            onClick={handleSubmit}
            disabled={submitting}
          >
            {submitting ? 'Creating...' : 'Create DNA Profile'}
          </Button>
        </Box>
      </Paper>
    </Box>
  );
}
